### ISSUE TITLE
(JS-0002) Avoid using `console` in code that runs on browser

### ISSUE THREAD

**Issue by sainAk** [mohitk0208/notes-pwa#1]
## Description
It is considered a best practice to avoid using any of `console`&#x27;s methods in JavaScript code that will run on the browser. Usually, `console` methods are only used for debugging, and can leak internal info to the client. &lt;!--more--&gt; ## Examples ### Bad Practice ```js console.log(&quot;Log a debug level message.&quot;); …

## Occurrences
There are 7 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mohitk0208/notes-pwa/issue/JS-0002/occurrences/](https://deepsource.io/gh/mohitk0208/notes-pwa/issue/JS-0002/occurrences/)

**Comment by mohitk0208** [comment]
console logs are required for debugging purpose during development, so they will exist in the **master** branch and the stable, sanitized and optimized code will be in the **production** branch
